# ref: https://hub.docker.com/_/mysql
version: '3.1'

services:

  db:  # Use root/root as user/password MySQL credentials
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
